### ISSUE TITLE
problem with upload avatar

### ISSUE THREAD

**Issue by inrussiawithhate** [thebatclaudio/socialdoor#4]
What is this: "Impossibile copiare la foto!" ?

**Comment by ClaudioLaBarbera** [comment]
LOL! Sorry but I don't work on SocialDoor for a lot of time. "Impossibile
copiare la foto" is an italian text that i didn't translate, it means "I
can't copy the picture".
Where do you get this error?
Il giorno gio 22 ott 2015 alle ore 21:29 inrussiawithhate <
notifications@github.com> ha scritto:
